### PR TITLE
Integrate fixed apr rari

### PR DESCRIPTION
**Pull request by danieledamiani**

### CODE REVIEW

**Comment by lazarmitic** [comment]
Do we have to keep whole rari sdk as a package in our repo?

**Comment by danieledamiani** [comment]
> Do we have to keep whole rari sdk as a package in our repo?

doesn't seem to be published so we have to

**Comment by lazarmitic** [comment]
> > Do we have to keep whole rari sdk as a package in our repo?
> 
> doesn't seem to be published so we have to

If they have this code in a public GitHub repo, we can iclude it as a git submodule instead of copy/pasting whole codebase.

**Review by ShawTim — DISMISSED** [review]
lgtm

**Comment by lazarmitic** [comment]
https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Review by lazarmitic — APPROVED** [review]

**Pull request merged**
