### PR TITLE
Remove wallet connected notification

### PR DESCRIPTION
**Pull request by danieledamiani**

### CODE REVIEW

**Comment by lazarmitic** [comment]
This is going to remove notification completely, I though we only wanted to remove notification when application opens (user refreshes the page?)

**Review by lazarmitic — COMMENTED** [review]
A comment, maybe I'm wrong, but I think we want to keep the notification when user clicks the button to connect the wallet.

**Comment by danieledamiani** [comment]
>

**Comment by danieledamiani** [comment]
> This is going to remove notification completely, I though we only wanted to remove notification when application opens (user refreshes the page?)

Refactored

**Review by lazarmitic — APPROVED** [review]

**Pull request merged**
